# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: GitAddCommit
before:
  hooks:
    - go mod tidy
builds:
  - binary: git-add-commit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
release:
  github:
    owner: rawnly
    name: git-add-commit

brews:
  -
    name: git-add-commit
    homepage: "https://github.com/rawnly/git-add-commit"
    license: "MIT"
    folder: Formula
    description: "Commit made easy"
    tap:
      owner: rawnly
      name: homebrew-tap
      branch: master
    dependencies:
      - git

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
announce:
  smtp:
    enabled: true
    host: "smtp.gmail.com"
    port: 587
    from: "releases@fedevitale.dev"
    to:
      - "newsletter@fedevitale.dev"
    username: "fedevitale99@gmail.com"