name: Release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main

permissions:
  contents: write
  
jobs:
  goreleaser:
    runs-on: ubunut-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run Release
        uses: goreleaser/goreleaser-action@v2
        if: github.event_name == 'pull_request'
        with:
          distrivution: goreleaser
          version: latest
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Run Release
        uses: goreleaser/goreleaser-action@v2
        if: github.event_name != 'pull_request'
        with:
          distrivution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
