name: Release

on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - '.github/*'
      - '*.md'
      - '.idea/*'
      - '.goreleaser.yml'
    branches: 
      - main
      - develop
      - 'feature/*'
      - 'hotfix/*'

permissions:
  contents: write
  
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      -
        name: PreRelease
        uses: goreleaser/goreleaser-action@v2
        if: github.event_name == 'pull_request' || github.ref_name != 'master' 
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Release
        uses: goreleaser/goreleaser-action@v2
        if: github.ref_name == 'master' && github.event_name != 'pull_request'
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
